#!/usr/bin/env bash

# This script starts a shell in a container running the libc++ build bot Docker
# image. That image emulates the environment used by libc++'s Linux builders on
# BuildKite.
#
# Once you're inside the shell, you can run the various build jobs with the
# `run-buildbot` script.
#
# This script must be run from within the LLVM monorepo. Furthermore, the
# monorepo will be mounted as `/llvm` inside the container. Be careful, the
# state in `/llvm` is shared between the container and the host machine, which
# is useful for editing files on the host machine and re-running the build bot
# in the container.
#
# If you are on Linux you will likely not be able to write to the mount because
# the user in the container doesn't have permissions to do so.
# If you need to do this, give that user permission to do so after running
# the container or add this flag to run the container as your local user IDs:
# --user $(id -u):$(id -g)

set -e

SKIP_PULL=0
while [[ ${#} -gt 0 ]]; do
    case "${1}" in
        --skip-pull) SKIP_PULL=1; shift ;;
        *) echo "error: unrecognized argument: ${1}" >&2 ; exit 1 ;;
    esac
done

MONOREPO_ROOT="$(git rev-parse --show-toplevel)"
if [[ ! -d "${MONOREPO_ROOT}/libcxx/utils/ci" ]]; then
    echo "Was unable to find the root of the LLVM monorepo; are you running from within the monorepo?"
    exit 1
fi

if [ ${SKIP_PULL} -eq 0 ]; then
    docker pull ldionne/libcxx-builder
fi

DOCKER_OPTIONS=(-it)
DOCKER_OPTIONS+=(--volume "${MONOREPO_ROOT}:/llvm")
DOCKER_OPTIONS+=(--workdir "/llvm")
DOCKER_OPTIONS+=(--cap-add=SYS_PTRACE)

# Mount this volume to allow the main image to share its copy of the Android
# platform tools with the emulator image, ensuring that the adb versions match.
# This argument will create a new volume if it doesn't already exist.
DOCKER_OPTIONS+=(--volume android-platform-tools:/mnt/android-platform-tools)

# Pass through the Docker socket so that the buildbot can start a sibling
# container running an Android emulator.
if [ -S /var/run/docker.sock ]; then
    DOCKER_OPTIONS+=(--volume /var/run/docker.sock:/var/run/docker.sock)
fi

docker run "${DOCKER_OPTIONS[@]}" ldionne/libcxx-builder \
    bash -c 'git config --global --add safe.directory /llvm; (/opt/bin/container-setup.sh && exec bash)'
