// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %clang_cc1 -triple x86_64-linux-gnu -target-cpu nehalem -emit-llvm -o - %s | FileCheck -check-prefixes=CHECK-NO-FMA %s
// RUN: %clang_cc1 -triple x86_64-linux-gnu -target-cpu skylake -emit-llvm -o - %s | FileCheck -check-prefixes=CHECK-FMA %s

// CHECK-NO-FMA-LABEL: define dso_local float @testFma
// CHECK-NO-FMA-SAME: (float noundef [[ADD:%.*]], float noundef [[MUL:%.*]], float noundef [[NUM:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NO-FMA-NEXT:  entry:
// CHECK-NO-FMA-NEXT:    [[ADD_ADDR:%.*]] = alloca float, align 4
// CHECK-NO-FMA-NEXT:    [[MUL_ADDR:%.*]] = alloca float, align 4
// CHECK-NO-FMA-NEXT:    [[NUM_ADDR:%.*]] = alloca float, align 4
// CHECK-NO-FMA-NEXT:    store float [[ADD]], ptr [[ADD_ADDR]], align 4
// CHECK-NO-FMA-NEXT:    store float [[MUL]], ptr [[MUL_ADDR]], align 4
// CHECK-NO-FMA-NEXT:    store float [[NUM]], ptr [[NUM_ADDR]], align 4
// CHECK-NO-FMA-NEXT:    [[TMP0:%.*]] = load float, ptr [[ADD_ADDR]], align 4
// CHECK-NO-FMA-NEXT:    [[TMP1:%.*]] = load float, ptr [[NUM_ADDR]], align 4
// CHECK-NO-FMA-NEXT:    [[TMP2:%.*]] = load float, ptr [[MUL_ADDR]], align 4
// CHECK-NO-FMA-NEXT:    [[MUL1:%.*]] = fmul float [[TMP1]], [[TMP2]]
// CHECK-NO-FMA-NEXT:    [[ADD2:%.*]] = fadd float [[TMP0]], [[MUL1]]
// CHECK-NO-FMA-NEXT:    ret float [[ADD2]]
//
// CHECK-FMA-LABEL: define dso_local float @testFma
// CHECK-FMA-SAME: (float noundef [[ADD:%.*]], float noundef [[MUL:%.*]], float noundef [[NUM:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-FMA-NEXT:  entry:
// CHECK-FMA-NEXT:    [[ADD_ADDR:%.*]] = alloca float, align 4
// CHECK-FMA-NEXT:    [[MUL_ADDR:%.*]] = alloca float, align 4
// CHECK-FMA-NEXT:    [[NUM_ADDR:%.*]] = alloca float, align 4
// CHECK-FMA-NEXT:    store float [[ADD]], ptr [[ADD_ADDR]], align 4
// CHECK-FMA-NEXT:    store float [[MUL]], ptr [[MUL_ADDR]], align 4
// CHECK-FMA-NEXT:    store float [[NUM]], ptr [[NUM_ADDR]], align 4
// CHECK-FMA-NEXT:    [[TMP0:%.*]] = load float, ptr [[ADD_ADDR]], align 4
// CHECK-FMA-NEXT:    [[TMP1:%.*]] = load float, ptr [[NUM_ADDR]], align 4
// CHECK-FMA-NEXT:    [[TMP2:%.*]] = load float, ptr [[MUL_ADDR]], align 4
// CHECK-FMA-NEXT:    [[TMP3:%.*]] = call float @llvm.fmuladd.f32(float [[TMP1]], float [[TMP2]], float [[TMP0]])
// CHECK-FMA-NEXT:    ret float [[TMP3]]
//
float testFma(float add, float mul, float num) {
    return add + num*mul;
}
