; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=aarch64-unknown-linux-gnu -mattr=+sme -S -passes=inline | FileCheck %s

declare void @inlined_streaming_body() "aarch64_pstate_sm_enabled";
declare void @inlined_locally_streaming_body() "aarch64_pstate_sm_body";
declare void @inlined_streaming_compatible_body() "aarch64_pstate_sm_compatible";
declare void @inlined_streaming_compatible_locally_streaming_body() "aarch64_pstate_sm_compatible" "aarch64_pstate_sm_body";
declare void @inlined_normal_body();

define void @streaming_callee() "aarch64_pstate_sm_enabled" {
; CHECK-LABEL: @streaming_callee(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_streaming_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @inlined_streaming_body()
  ret void
}

define void @locally_streaming_callee() "aarch64_pstate_sm_body" {
; CHECK-LABEL: @locally_streaming_callee(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_locally_streaming_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @inlined_locally_streaming_body()
  ret void
}

define void @streaming_compatible_callee() "aarch64_pstate_sm_compatible" {
; CHECK-LABEL: @streaming_compatible_callee(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_streaming_compatible_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @inlined_streaming_compatible_body()
  ret void
}

define void @streaming_compatible_locally_streaming_callee() "aarch64_pstate_sm_compatible" "aarch64_pstate_sm_body" {
; CHECK-LABEL: @streaming_compatible_locally_streaming_callee(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_streaming_compatible_locally_streaming_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @inlined_streaming_compatible_locally_streaming_body()
  ret void
}

define void @normal_callee() {
; CHECK-LABEL: @normal_callee(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_normal_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @inlined_normal_body()
  ret void
}

define void @streaming_caller_streaming_callee_inline() "aarch64_pstate_sm_enabled" {
; CHECK-LABEL: @streaming_caller_streaming_callee_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_streaming_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @streaming_callee()
  ret void
}

define void @streaming_caller_locally_streaming_callee_inline() "aarch64_pstate_sm_enabled" {
; CHECK-LABEL: @streaming_caller_locally_streaming_callee_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_locally_streaming_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @locally_streaming_callee()
  ret void
}

define void @streaming_caller_streaming_compatible_callee_inline() "aarch64_pstate_sm_enabled" {
; CHECK-LABEL: @streaming_caller_streaming_compatible_callee_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_streaming_compatible_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @streaming_compatible_callee()
  ret void
}

define void @streaming_caller_streaming_compatible_locally_streaming_callee_inline() "aarch64_pstate_sm_enabled" {
; CHECK-LABEL: @streaming_caller_streaming_compatible_locally_streaming_callee_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_streaming_compatible_locally_streaming_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @streaming_compatible_locally_streaming_callee()
  ret void
}

define void @streaming_caller_normal_callee_dont_inline() "aarch64_pstate_sm_enabled" {
; CHECK-LABEL: @streaming_caller_normal_callee_dont_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @normal_callee()
; CHECK-NEXT:    ret void
;
entry:
  call void @normal_callee()
  ret void
}

define void @locally_streaming_caller_streaming_callee_inline() "aarch64_pstate_sm_body" {
; CHECK-LABEL: @locally_streaming_caller_streaming_callee_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_streaming_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @streaming_callee()
  ret void
}

define void @locally_streaming_caller_locally_streaming_callee_inline() "aarch64_pstate_sm_body" {
; CHECK-LABEL: @locally_streaming_caller_locally_streaming_callee_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_locally_streaming_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @locally_streaming_callee()
  ret void
}

define void @locally_streaming_caller_streaming_compatible_callee_inline() "aarch64_pstate_sm_body" {
; CHECK-LABEL: @locally_streaming_caller_streaming_compatible_callee_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_streaming_compatible_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @streaming_compatible_callee()
  ret void
}

define void @locally_streaming_caller_streaming_compatible_locally_streaming_callee_inline() "aarch64_pstate_sm_body" {
; CHECK-LABEL: @locally_streaming_caller_streaming_compatible_locally_streaming_callee_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_streaming_compatible_locally_streaming_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @streaming_compatible_locally_streaming_callee()
  ret void
}

define void @locally_streaming_caller_normal_callee_dont_inline() "aarch64_pstate_sm_body" {
; CHECK-LABEL: @locally_streaming_caller_normal_callee_dont_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @normal_callee()
; CHECK-NEXT:    ret void
;
entry:
  call void @normal_callee()
  ret void
}

define void @streaming_compatible_caller_streaming_callee_dont_inline() "aarch64_pstate_sm_compatible" {
; CHECK-LABEL: @streaming_compatible_caller_streaming_callee_dont_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @streaming_callee()
; CHECK-NEXT:    ret void
;
entry:
  call void @streaming_callee()
  ret void
}

define void @streaming_compatible_caller_locally_streaming_callee_dont_inline() "aarch64_pstate_sm_compatible" {
; CHECK-LABEL: @streaming_compatible_caller_locally_streaming_callee_dont_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @locally_streaming_callee()
; CHECK-NEXT:    ret void
;
entry:
  call void @locally_streaming_callee()
  ret void
}

define void @streaming_compatible_caller_streaming_compatible_callee_inline() "aarch64_pstate_sm_compatible" {
; CHECK-LABEL: @streaming_compatible_caller_streaming_compatible_callee_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_streaming_compatible_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @streaming_compatible_callee()
  ret void
}

define void @streaming_compatible_caller_streaming_compatible_locally_streaming_callee_dont_inline() "aarch64_pstate_sm_compatible" {
; CHECK-LABEL: @streaming_compatible_caller_streaming_compatible_locally_streaming_callee_dont_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @streaming_compatible_locally_streaming_callee()
; CHECK-NEXT:    ret void
;
entry:
  call void @streaming_compatible_locally_streaming_callee()
  ret void
}

define void @streaming_compatible_caller_normal_callee_dont_inline() "aarch64_pstate_sm_compatible" {
; CHECK-LABEL: @streaming_compatible_caller_normal_callee_dont_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @normal_callee()
; CHECK-NEXT:    ret void
;
entry:
  call void @normal_callee()
  ret void
}

define void @normal_caller_streaming_callee_dont_inline() {
; CHECK-LABEL: @normal_caller_streaming_callee_dont_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @streaming_callee()
; CHECK-NEXT:    ret void
;
entry:
  call void @streaming_callee()
  ret void
}

define void @normal_caller_locally_streaming_callee_dont_inline() {
; CHECK-LABEL: @normal_caller_locally_streaming_callee_dont_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @locally_streaming_callee()
; CHECK-NEXT:    ret void
;
entry:
  call void @locally_streaming_callee()
  ret void
}

define void @normal_caller_streaming_compatible_callee_inline() {
; CHECK-LABEL: @normal_caller_streaming_compatible_callee_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_streaming_compatible_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @streaming_compatible_callee()
  ret void
}

define void @normal_caller_streaming_compatible_locally_streaming_callee_dont_inline() {
; CHECK-LABEL: @normal_caller_streaming_compatible_locally_streaming_callee_dont_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @streaming_compatible_locally_streaming_callee()
; CHECK-NEXT:    ret void
;
entry:
  call void @streaming_compatible_locally_streaming_callee()
  ret void
}

define void @normal_caller_normal_callee_inline() {
; CHECK-LABEL: @normal_caller_normal_callee_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_normal_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @normal_callee()
  ret void
}


define void @streaming_compatible_locally_streaming_caller_streaming_callee_inline() "aarch64_pstate_sm_compatible" "aarch64_pstate_sm_body" {
; CHECK-LABEL: @streaming_compatible_locally_streaming_caller_streaming_callee_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_streaming_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @streaming_callee()
  ret void
}

define void @streaming_compatible_locally_streaming_caller_locally_streaming_callee_inline() "aarch64_pstate_sm_compatible" "aarch64_pstate_sm_body" {
; CHECK-LABEL: @streaming_compatible_locally_streaming_caller_locally_streaming_callee_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_locally_streaming_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @locally_streaming_callee()
  ret void
}

define void @streaming_compatible_locally_streaming_caller_streaming_compatible_callee_inline() "aarch64_pstate_sm_compatible" "aarch64_pstate_sm_body" {
; CHECK-LABEL: @streaming_compatible_locally_streaming_caller_streaming_compatible_callee_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_streaming_compatible_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @streaming_compatible_callee()
  ret void
}

define void @streaming_compatible_locally_streaming_caller_and_callee_inline() "aarch64_pstate_sm_compatible" "aarch64_pstate_sm_body" {
; CHECK-LABEL: @streaming_compatible_locally_streaming_caller_and_callee_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @inlined_streaming_compatible_locally_streaming_body()
; CHECK-NEXT:    ret void
;
entry:
  call void @streaming_compatible_locally_streaming_callee()
  ret void
}

define void @streaming_compatible_locally_streaming_caller_normal_callee_dont_inline() "aarch64_pstate_sm_compatible" "aarch64_pstate_sm_body" {
; CHECK-LABEL: @streaming_compatible_locally_streaming_caller_normal_callee_dont_inline(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    call void @normal_callee()
; CHECK-NEXT:    ret void
;
entry:
  call void @normal_callee()
  ret void
}
