# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -march=riscv32 -run-pass=instruction-select -simplify-mir -verify-machineinstrs %s -o - \
# RUN: | FileCheck -check-prefix=RV32I %s
---
name:            cmp_ult_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: cmp_ult_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I-NEXT: [[SLTU:%[0-9]+]]:gpr = SLTU [[COPY]], [[COPY1]]
    ; RV32I-NEXT: $x10 = COPY [[SLTU]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ICMP intpred(ult), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_slt_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: cmp_slt_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I-NEXT: [[SLT:%[0-9]+]]:gpr = SLT [[COPY]], [[COPY1]]
    ; RV32I-NEXT: $x10 = COPY [[SLT]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ICMP intpred(slt), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_ugt_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: cmp_ugt_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I-NEXT: [[SLTU:%[0-9]+]]:gpr = SLTU [[COPY1]], [[COPY]]
    ; RV32I-NEXT: $x10 = COPY [[SLTU]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ICMP intpred(ugt), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_sgt_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: cmp_sgt_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I-NEXT: [[SLT:%[0-9]+]]:gpr = SLT [[COPY1]], [[COPY]]
    ; RV32I-NEXT: $x10 = COPY [[SLT]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ICMP intpred(sgt), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_eq_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: cmp_eq_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I-NEXT: [[XOR:%[0-9]+]]:gpr = XOR [[COPY]], [[COPY1]]
    ; RV32I-NEXT: [[SLTIU:%[0-9]+]]:gpr = SLTIU [[XOR]], 1
    ; RV32I-NEXT: $x10 = COPY [[SLTIU]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ICMP intpred(eq), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_ne_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: cmp_ne_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I-NEXT: [[XOR:%[0-9]+]]:gpr = XOR [[COPY]], [[COPY1]]
    ; RV32I-NEXT: [[SLTU:%[0-9]+]]:gpr = SLTU $x0, [[XOR]]
    ; RV32I-NEXT: $x10 = COPY [[SLTU]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ICMP intpred(ne), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_ule_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: cmp_ule_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I-NEXT: [[SLTU:%[0-9]+]]:gpr = SLTU [[COPY]], [[COPY1]]
    ; RV32I-NEXT: [[XORI:%[0-9]+]]:gpr = XORI [[SLTU]], 1
    ; RV32I-NEXT: $x10 = COPY [[XORI]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ICMP intpred(ule), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_sle_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: cmp_sle_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I-NEXT: [[SLT:%[0-9]+]]:gpr = SLT [[COPY]], [[COPY1]]
    ; RV32I-NEXT: [[XORI:%[0-9]+]]:gpr = XORI [[SLT]], 1
    ; RV32I-NEXT: $x10 = COPY [[XORI]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ICMP intpred(sle), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_uge_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: cmp_uge_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I-NEXT: [[SLTU:%[0-9]+]]:gpr = SLTU [[COPY1]], [[COPY]]
    ; RV32I-NEXT: [[XORI:%[0-9]+]]:gpr = XORI [[SLTU]], 1
    ; RV32I-NEXT: $x10 = COPY [[XORI]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ICMP intpred(uge), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_sge_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10, $x11

    ; RV32I-LABEL: name: cmp_sge_i32
    ; RV32I: liveins: $x10, $x11
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x11
    ; RV32I-NEXT: [[SLT:%[0-9]+]]:gpr = SLT [[COPY1]], [[COPY]]
    ; RV32I-NEXT: [[XORI:%[0-9]+]]:gpr = XORI [[SLT]], 1
    ; RV32I-NEXT: $x10 = COPY [[XORI]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = COPY $x11
    %2:gprb(s32) = G_ICMP intpred(sge), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_ulti_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10

    ; RV32I-LABEL: name: cmp_ulti_i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[SLTIU:%[0-9]+]]:gpr = SLTIU [[COPY]], 10
    ; RV32I-NEXT: $x10 = COPY [[SLTIU]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = G_CONSTANT i32 10
    %2:gprb(s32) = G_ICMP intpred(ult), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_slti_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10

    ; RV32I-LABEL: name: cmp_slti_i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[SLTI:%[0-9]+]]:gpr = SLTI [[COPY]], 10
    ; RV32I-NEXT: $x10 = COPY [[SLTI]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = G_CONSTANT i32 10
    %2:gprb(s32) = G_ICMP intpred(slt), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_ugti_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10

    ; RV32I-LABEL: name: cmp_ugti_i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[SLTIU:%[0-9]+]]:gpr = SLTIU [[COPY]], 11
    ; RV32I-NEXT: [[XORI:%[0-9]+]]:gpr = XORI [[SLTIU]], 1
    ; RV32I-NEXT: $x10 = COPY [[XORI]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = G_CONSTANT i32 10
    %2:gprb(s32) = G_ICMP intpred(ugt), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_sgti_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10

    ; RV32I-LABEL: name: cmp_sgti_i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[SLTI:%[0-9]+]]:gpr = SLTI [[COPY]], 11
    ; RV32I-NEXT: [[XORI:%[0-9]+]]:gpr = XORI [[SLTI]], 1
    ; RV32I-NEXT: $x10 = COPY [[XORI]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = G_CONSTANT i32 10
    %2:gprb(s32) = G_ICMP intpred(sgt), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_eqi_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10

    ; RV32I-LABEL: name: cmp_eqi_i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[ADDI:%[0-9]+]]:gpr = ADDI [[COPY]], 9
    ; RV32I-NEXT: [[SLTIU:%[0-9]+]]:gpr = SLTIU [[ADDI]], 1
    ; RV32I-NEXT: $x10 = COPY [[SLTIU]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = G_CONSTANT i32 10
    %2:gprb(s32) = G_ICMP intpred(eq), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_nei_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10

    ; RV32I-LABEL: name: cmp_nei_i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[ADDI:%[0-9]+]]:gpr = ADDI [[COPY]], 9
    ; RV32I-NEXT: [[SLTU:%[0-9]+]]:gpr = SLTU $x0, [[ADDI]]
    ; RV32I-NEXT: $x10 = COPY [[SLTU]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = G_CONSTANT i32 10
    %2:gprb(s32) = G_ICMP intpred(ne), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_ulei_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10

    ; RV32I-LABEL: name: cmp_ulei_i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[ADDI:%[0-9]+]]:gpr = ADDI $x0, 10
    ; RV32I-NEXT: [[SLTU:%[0-9]+]]:gpr = SLTU [[COPY]], [[ADDI]]
    ; RV32I-NEXT: [[XORI:%[0-9]+]]:gpr = XORI [[SLTU]], 1
    ; RV32I-NEXT: $x10 = COPY [[XORI]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = G_CONSTANT i32 10
    %2:gprb(s32) = G_ICMP intpred(ule), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_slei_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10

    ; RV32I-LABEL: name: cmp_slei_i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[ADDI:%[0-9]+]]:gpr = ADDI $x0, 10
    ; RV32I-NEXT: [[SLT:%[0-9]+]]:gpr = SLT [[COPY]], [[ADDI]]
    ; RV32I-NEXT: [[XORI:%[0-9]+]]:gpr = XORI [[SLT]], 1
    ; RV32I-NEXT: $x10 = COPY [[XORI]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = G_CONSTANT i32 10
    %2:gprb(s32) = G_ICMP intpred(sle), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_ugei_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10

    ; RV32I-LABEL: name: cmp_ugei_i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[ADDI:%[0-9]+]]:gpr = ADDI $x0, 10
    ; RV32I-NEXT: [[SLTU:%[0-9]+]]:gpr = SLTU [[ADDI]], [[COPY]]
    ; RV32I-NEXT: [[XORI:%[0-9]+]]:gpr = XORI [[SLTU]], 1
    ; RV32I-NEXT: $x10 = COPY [[XORI]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = G_CONSTANT i32 10
    %2:gprb(s32) = G_ICMP intpred(uge), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_sgei_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10

    ; RV32I-LABEL: name: cmp_sgei_i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[ADDI:%[0-9]+]]:gpr = ADDI $x0, 10
    ; RV32I-NEXT: [[SLT:%[0-9]+]]:gpr = SLT [[ADDI]], [[COPY]]
    ; RV32I-NEXT: [[XORI:%[0-9]+]]:gpr = XORI [[SLT]], 1
    ; RV32I-NEXT: $x10 = COPY [[XORI]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = G_CONSTANT i32 10
    %2:gprb(s32) = G_ICMP intpred(sge), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_eq0_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10

    ; RV32I-LABEL: name: cmp_eq0_i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[SLTIU:%[0-9]+]]:gpr = SLTIU [[COPY]], 1
    ; RV32I-NEXT: $x10 = COPY [[SLTIU]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = G_CONSTANT i32 0
    %2:gprb(s32) = G_ICMP intpred(eq), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_ne0_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10

    ; RV32I-LABEL: name: cmp_ne0_i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x10
    ; RV32I-NEXT: [[SLTU:%[0-9]+]]:gpr = SLTU $x0, [[COPY]]
    ; RV32I-NEXT: $x10 = COPY [[SLTU]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = G_CONSTANT i32 0
    %2:gprb(s32) = G_ICMP intpred(ne), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
---
name:            cmp_ugt_neg1_i32
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.0.entry:
    liveins: $x10

    ; RV32I-LABEL: name: cmp_ugt_neg1_i32
    ; RV32I: liveins: $x10
    ; RV32I-NEXT: {{  $}}
    ; RV32I-NEXT: [[ADDI:%[0-9]+]]:gpr = ADDI $x0, 0
    ; RV32I-NEXT: $x10 = COPY [[ADDI]]
    ; RV32I-NEXT: PseudoRET implicit $x10
    %0:gprb(s32) = COPY $x10
    %1:gprb(s32) = G_CONSTANT i32 -1
    %2:gprb(s32) = G_ICMP intpred(ugt), %0, %1
    $x10 = COPY %2(s32)
    PseudoRET implicit $x10

...
