// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: aarch64-registered-target
// RUN: %clang_cc1 -triple aarch64-none-linux-gnu -target-feature +sme -S -O1 -Werror -emit-llvm -o - %s | FileCheck %s
// RUN: %clang_cc1 -triple aarch64-none-linux-gnu -target-feature +sme -S -O1 -Werror -emit-llvm -o - -x c++ %s | FileCheck %s -check-prefix=CPP-CHECK
// RUN: %clang_cc1 -triple aarch64-none-linux-gnu -target-feature +sme -S -disable-O0-optnone -Werror -Wall -o /dev/null %s

#include <arm_sme.h>

// CHECK-LABEL: @test_arm_sc_memcpy(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @__arm_sc_memcpy(ptr noundef [[DEST:%.*]], ptr noundef [[SRC:%.*]], i64 noundef [[N:%.*]]) #[[ATTR2:[0-9]+]]
// CHECK-NEXT:    ret ptr [[CALL]]
//
// CPP-CHECK-LABEL: @_Z18test_arm_sc_memcpyPvPKvm(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @__arm_sc_memcpy(ptr noundef [[DEST:%.*]], ptr noundef [[SRC:%.*]], i64 noundef [[N:%.*]]) #[[ATTR2:[0-9]+]]
// CPP-CHECK-NEXT:    ret ptr [[CALL]]
//
__attribute__((arm_streaming_compatible))
void *test_arm_sc_memcpy(void *dest, const void *src, size_t n) {
  return __arm_sc_memcpy(dest, src, n);
}

// CHECK-LABEL: @test_arm_sc_memmove(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @__arm_sc_memmove(ptr noundef [[DEST:%.*]], ptr noundef [[SRC:%.*]], i64 noundef [[N:%.*]]) #[[ATTR2]]
// CHECK-NEXT:    ret ptr [[CALL]]
//
// CPP-CHECK-LABEL: @_Z19test_arm_sc_memmovePvPKvm(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @__arm_sc_memmove(ptr noundef [[DEST:%.*]], ptr noundef [[SRC:%.*]], i64 noundef [[N:%.*]]) #[[ATTR2]]
// CPP-CHECK-NEXT:    ret ptr [[CALL]]
//
__attribute__((arm_streaming_compatible))
void *test_arm_sc_memmove(void *dest, const void *src, size_t n) {
  return __arm_sc_memmove(dest, src, n);
}

// CHECK-LABEL: @test_arm_sc_memset(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @__arm_sc_memset(ptr noundef [[DEST:%.*]], i32 noundef [[C:%.*]], i64 noundef [[N:%.*]]) #[[ATTR2]]
// CHECK-NEXT:    ret ptr [[CALL]]
//
// CPP-CHECK-LABEL: @_Z18test_arm_sc_memsetPvim(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @__arm_sc_memset(ptr noundef [[DEST:%.*]], i32 noundef [[C:%.*]], i64 noundef [[N:%.*]]) #[[ATTR2]]
// CPP-CHECK-NEXT:    ret ptr [[CALL]]
//
__attribute__((arm_streaming_compatible))
void *test_arm_sc_memset(void *dest, int c, size_t n) {
  return __arm_sc_memset(dest, c, n);
}

// CHECK-LABEL: @test_arm_sc_memchr(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @__arm_sc_memchr(ptr noundef [[DEST:%.*]], i32 noundef [[C:%.*]], i64 noundef [[N:%.*]]) #[[ATTR2]]
// CHECK-NEXT:    ret ptr [[CALL]]
//
// CPP-CHECK-LABEL: @_Z18test_arm_sc_memchrPvim(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[CALL:%.*]] = tail call ptr @__arm_sc_memchr(ptr noundef [[DEST:%.*]], i32 noundef [[C:%.*]], i64 noundef [[N:%.*]]) #[[ATTR2]]
// CPP-CHECK-NEXT:    ret ptr [[CALL]]
//
__attribute__((arm_streaming_compatible))
void *test_arm_sc_memchr(void *dest, int c, size_t n) {
  return __arm_sc_memchr(dest, c, n);
}
