// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// REQUIRES: aarch64-registered-target
// RUN: %clang_cc1 -triple aarch64-none-linux-gnu -target-feature +sme -S -O1 -Werror -emit-llvm -o - %s | FileCheck %s
// RUN: %clang_cc1 -triple aarch64-none-linux-gnu -target-feature +sme -S -O1 -Werror -emit-llvm -o - -x c++ %s | FileCheck %s -check-prefix=CPP-CHECK
// RUN: %clang_cc1 -triple aarch64-none-linux-gnu -target-feature +sme -S -disable-O0-optnone -Werror -Wall -o /dev/null %s

#include <arm_sme.h>

// == HORIZONTAL ==

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_hor_za8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 15
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1b.horiz(<vscale x 16 x i1> [[PG:%.*]], ptr [[BASE:%.*]], i32 0, i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z18test_svst1_hor_za8ju10__SVBool_tPa(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 15
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1b.horiz(<vscale x 16 x i1> [[PG:%.*]], ptr [[BASE:%.*]], i32 0, i32 [[TMP0]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_hor_za8(uint32_t slice_base, svbool_t pg, int8_t *base) {
  svst1_hor_za8(0, slice_base, 15, pg, base);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_hor_za16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 7
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 8 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv8i1(<vscale x 16 x i1> [[PG:%.*]])
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1h.horiz(<vscale x 8 x i1> [[TMP1]], ptr [[BASE:%.*]], i32 1, i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z19test_svst1_hor_za16ju10__SVBool_tPs(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 7
// CPP-CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 8 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv8i1(<vscale x 16 x i1> [[PG:%.*]])
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1h.horiz(<vscale x 8 x i1> [[TMP1]], ptr [[BASE:%.*]], i32 1, i32 [[TMP0]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_hor_za16(uint32_t slice_base, svbool_t pg, int16_t *base) {
  svst1_hor_za16(1, slice_base, 7, pg, base);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_hor_za32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 3
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 4 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv4i1(<vscale x 16 x i1> [[PG:%.*]])
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1w.horiz(<vscale x 4 x i1> [[TMP1]], ptr [[BASE:%.*]], i32 3, i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z19test_svst1_hor_za32ju10__SVBool_tPi(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 3
// CPP-CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 4 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv4i1(<vscale x 16 x i1> [[PG:%.*]])
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1w.horiz(<vscale x 4 x i1> [[TMP1]], ptr [[BASE:%.*]], i32 3, i32 [[TMP0]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_hor_za32(uint32_t slice_base, svbool_t pg, int32_t *base) {
  svst1_hor_za32(3, slice_base, 3, pg, base);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_hor_za64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 1
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 2 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv2i1(<vscale x 16 x i1> [[PG:%.*]])
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1d.horiz(<vscale x 2 x i1> [[TMP1]], ptr [[BASE:%.*]], i32 7, i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z19test_svst1_hor_za64ju10__SVBool_tPl(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 1
// CPP-CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 2 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv2i1(<vscale x 16 x i1> [[PG:%.*]])
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1d.horiz(<vscale x 2 x i1> [[TMP1]], ptr [[BASE:%.*]], i32 7, i32 [[TMP0]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_hor_za64(uint32_t slice_base, svbool_t pg, int64_t *base) {
  svst1_hor_za64(7, slice_base, 1, pg, base);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_hor_za128(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[PG:%.*]])
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1q.horiz(<vscale x 1 x i1> [[TMP0]], ptr [[BASE:%.*]], i32 15, i32 [[SLICE_BASE:%.*]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z20test_svst1_hor_za128ju10__SVBool_tPn(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[PG:%.*]])
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1q.horiz(<vscale x 1 x i1> [[TMP0]], ptr [[BASE:%.*]], i32 15, i32 [[SLICE_BASE:%.*]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_hor_za128(uint32_t slice_base, svbool_t pg, __int128_t *base) {
  svst1_hor_za128(15, slice_base, 0, pg, base);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_hor_vnum_za8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 15
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CHECK-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 3
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP2]]
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1b.horiz(<vscale x 16 x i1> [[PG:%.*]], ptr [[TMP3]], i32 0, i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z23test_svst1_hor_vnum_za8ju10__SVBool_tPa(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 15
// CPP-CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CPP-CHECK-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 3
// CPP-CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP2]]
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1b.horiz(<vscale x 16 x i1> [[PG:%.*]], ptr [[TMP3]], i32 0, i32 [[TMP0]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_hor_vnum_za8(uint32_t slice_base, svbool_t pg, int8_t *base) {
  svst1_hor_vnum_za8(0, slice_base, 15, pg, base, 3);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_hor_vnum_za16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 7
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 8 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv8i1(<vscale x 16 x i1> [[PG:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CHECK-NEXT:    [[TMP3:%.*]] = mul i64 [[TMP2]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP3]]
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1h.horiz(<vscale x 8 x i1> [[TMP1]], ptr [[TMP4]], i32 1, i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z24test_svst1_hor_vnum_za16ju10__SVBool_tPs(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 7
// CPP-CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 8 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv8i1(<vscale x 16 x i1> [[PG:%.*]])
// CPP-CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CPP-CHECK-NEXT:    [[TMP3:%.*]] = mul i64 [[TMP2]], 3
// CPP-CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP3]]
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1h.horiz(<vscale x 8 x i1> [[TMP1]], ptr [[TMP4]], i32 1, i32 [[TMP0]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_hor_vnum_za16(uint32_t slice_base, svbool_t pg, int16_t *base) {
  svst1_hor_vnum_za16(1, slice_base, 7, pg, base, 3);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_hor_vnum_za32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 3
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 4 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv4i1(<vscale x 16 x i1> [[PG:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CHECK-NEXT:    [[TMP3:%.*]] = mul i64 [[TMP2]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP3]]
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1w.horiz(<vscale x 4 x i1> [[TMP1]], ptr [[TMP4]], i32 3, i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z24test_svst1_hor_vnum_za32ju10__SVBool_tPi(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 3
// CPP-CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 4 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv4i1(<vscale x 16 x i1> [[PG:%.*]])
// CPP-CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CPP-CHECK-NEXT:    [[TMP3:%.*]] = mul i64 [[TMP2]], 3
// CPP-CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP3]]
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1w.horiz(<vscale x 4 x i1> [[TMP1]], ptr [[TMP4]], i32 3, i32 [[TMP0]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_hor_vnum_za32(uint32_t slice_base, svbool_t pg, int32_t *base) {
  svst1_hor_vnum_za32(3, slice_base, 3, pg, base, 3);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_hor_vnum_za64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 1
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 2 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv2i1(<vscale x 16 x i1> [[PG:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CHECK-NEXT:    [[TMP3:%.*]] = mul i64 [[TMP2]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP3]]
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1d.horiz(<vscale x 2 x i1> [[TMP1]], ptr [[TMP4]], i32 7, i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z24test_svst1_hor_vnum_za64ju10__SVBool_tPl(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 1
// CPP-CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 2 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv2i1(<vscale x 16 x i1> [[PG:%.*]])
// CPP-CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CPP-CHECK-NEXT:    [[TMP3:%.*]] = mul i64 [[TMP2]], 3
// CPP-CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP3]]
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1d.horiz(<vscale x 2 x i1> [[TMP1]], ptr [[TMP4]], i32 7, i32 [[TMP0]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_hor_vnum_za64(uint32_t slice_base, svbool_t pg, int64_t *base) {
  svst1_hor_vnum_za64(7, slice_base, 1, pg, base, 3);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_hor_vnum_za128(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[PG:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CHECK-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 3
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP2]]
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1q.horiz(<vscale x 1 x i1> [[TMP0]], ptr [[TMP3]], i32 15, i32 [[SLICE_BASE:%.*]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z25test_svst1_hor_vnum_za128ju10__SVBool_tPn(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[PG:%.*]])
// CPP-CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CPP-CHECK-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 3
// CPP-CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP2]]
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1q.horiz(<vscale x 1 x i1> [[TMP0]], ptr [[TMP3]], i32 15, i32 [[SLICE_BASE:%.*]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_hor_vnum_za128(uint32_t slice_base, svbool_t pg, __int128_t *base) {
  svst1_hor_vnum_za128(15, slice_base, 0, pg, base, 3);
}

// == VERTICAL ==

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_ver_za8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 15
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1b.vert(<vscale x 16 x i1> [[PG:%.*]], ptr [[BASE:%.*]], i32 0, i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z18test_svst1_ver_za8ju10__SVBool_tPa(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 15
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1b.vert(<vscale x 16 x i1> [[PG:%.*]], ptr [[BASE:%.*]], i32 0, i32 [[TMP0]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_ver_za8(uint32_t slice_base, svbool_t pg, int8_t *base) {
  svst1_ver_za8(0, slice_base, 15, pg, base);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_ver_za16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 7
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 8 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv8i1(<vscale x 16 x i1> [[PG:%.*]])
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1h.vert(<vscale x 8 x i1> [[TMP1]], ptr [[BASE:%.*]], i32 1, i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z19test_svst1_ver_za16ju10__SVBool_tPs(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 7
// CPP-CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 8 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv8i1(<vscale x 16 x i1> [[PG:%.*]])
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1h.vert(<vscale x 8 x i1> [[TMP1]], ptr [[BASE:%.*]], i32 1, i32 [[TMP0]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_ver_za16(uint32_t slice_base, svbool_t pg, int16_t *base) {
  svst1_ver_za16(1, slice_base, 7, pg, base);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_ver_za32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 3
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 4 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv4i1(<vscale x 16 x i1> [[PG:%.*]])
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1w.vert(<vscale x 4 x i1> [[TMP1]], ptr [[BASE:%.*]], i32 3, i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z19test_svst1_ver_za32ju10__SVBool_tPi(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 3
// CPP-CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 4 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv4i1(<vscale x 16 x i1> [[PG:%.*]])
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1w.vert(<vscale x 4 x i1> [[TMP1]], ptr [[BASE:%.*]], i32 3, i32 [[TMP0]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_ver_za32(uint32_t slice_base, svbool_t pg, int32_t *base) {
  svst1_ver_za32(3, slice_base, 3, pg, base);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_ver_za64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 1
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 2 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv2i1(<vscale x 16 x i1> [[PG:%.*]])
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1d.vert(<vscale x 2 x i1> [[TMP1]], ptr [[BASE:%.*]], i32 7, i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z19test_svst1_ver_za64ju10__SVBool_tPl(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 1
// CPP-CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 2 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv2i1(<vscale x 16 x i1> [[PG:%.*]])
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1d.vert(<vscale x 2 x i1> [[TMP1]], ptr [[BASE:%.*]], i32 7, i32 [[TMP0]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_ver_za64(uint32_t slice_base, svbool_t pg, int64_t *base) {
  svst1_ver_za64(7, slice_base, 1, pg, base);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_ver_za128(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[PG:%.*]])
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1q.vert(<vscale x 1 x i1> [[TMP0]], ptr [[BASE:%.*]], i32 15, i32 [[SLICE_BASE:%.*]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z20test_svst1_ver_za128ju10__SVBool_tPn(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[PG:%.*]])
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1q.vert(<vscale x 1 x i1> [[TMP0]], ptr [[BASE:%.*]], i32 15, i32 [[SLICE_BASE:%.*]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_ver_za128(uint32_t slice_base, svbool_t pg, __int128_t *base) {
  svst1_ver_za128(15, slice_base, 0, pg, base);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_ver_vnum_za8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 15
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CHECK-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 3
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP2]]
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1b.vert(<vscale x 16 x i1> [[PG:%.*]], ptr [[TMP3]], i32 0, i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z23test_svst1_ver_vnum_za8ju10__SVBool_tPa(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 15
// CPP-CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CPP-CHECK-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 3
// CPP-CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP2]]
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1b.vert(<vscale x 16 x i1> [[PG:%.*]], ptr [[TMP3]], i32 0, i32 [[TMP0]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_ver_vnum_za8(uint32_t slice_base, svbool_t pg, int8_t *base) {
  svst1_ver_vnum_za8(0, slice_base, 15, pg, base, 3);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_ver_vnum_za16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 7
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 8 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv8i1(<vscale x 16 x i1> [[PG:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CHECK-NEXT:    [[TMP3:%.*]] = mul i64 [[TMP2]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP3]]
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1h.vert(<vscale x 8 x i1> [[TMP1]], ptr [[TMP4]], i32 1, i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z24test_svst1_ver_vnum_za16ju10__SVBool_tPs(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 7
// CPP-CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 8 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv8i1(<vscale x 16 x i1> [[PG:%.*]])
// CPP-CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CPP-CHECK-NEXT:    [[TMP3:%.*]] = mul i64 [[TMP2]], 3
// CPP-CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP3]]
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1h.vert(<vscale x 8 x i1> [[TMP1]], ptr [[TMP4]], i32 1, i32 [[TMP0]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_ver_vnum_za16(uint32_t slice_base, svbool_t pg, int16_t *base) {
  svst1_ver_vnum_za16(1, slice_base, 7, pg, base, 3);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_ver_vnum_za32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 3
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 4 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv4i1(<vscale x 16 x i1> [[PG:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CHECK-NEXT:    [[TMP3:%.*]] = mul i64 [[TMP2]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP3]]
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1w.vert(<vscale x 4 x i1> [[TMP1]], ptr [[TMP4]], i32 3, i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z24test_svst1_ver_vnum_za32ju10__SVBool_tPi(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 3
// CPP-CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 4 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv4i1(<vscale x 16 x i1> [[PG:%.*]])
// CPP-CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CPP-CHECK-NEXT:    [[TMP3:%.*]] = mul i64 [[TMP2]], 3
// CPP-CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP3]]
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1w.vert(<vscale x 4 x i1> [[TMP1]], ptr [[TMP4]], i32 3, i32 [[TMP0]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_ver_vnum_za32(uint32_t slice_base, svbool_t pg, int32_t *base) {
  svst1_ver_vnum_za32(3, slice_base, 3, pg, base, 3);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_ver_vnum_za64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 1
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 2 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv2i1(<vscale x 16 x i1> [[PG:%.*]])
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CHECK-NEXT:    [[TMP3:%.*]] = mul i64 [[TMP2]], 3
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP3]]
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1d.vert(<vscale x 2 x i1> [[TMP1]], ptr [[TMP4]], i32 7, i32 [[TMP0]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z24test_svst1_ver_vnum_za64ju10__SVBool_tPl(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[SLICE_BASE:%.*]], 1
// CPP-CHECK-NEXT:    [[TMP1:%.*]] = tail call <vscale x 2 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv2i1(<vscale x 16 x i1> [[PG:%.*]])
// CPP-CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CPP-CHECK-NEXT:    [[TMP3:%.*]] = mul i64 [[TMP2]], 3
// CPP-CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP3]]
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1d.vert(<vscale x 2 x i1> [[TMP1]], ptr [[TMP4]], i32 7, i32 [[TMP0]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_ver_vnum_za64(uint32_t slice_base, svbool_t pg, int64_t *base) {
  svst1_ver_vnum_za64(7, slice_base, 1, pg, base, 3);
}

//
//
__attribute__((arm_streaming, arm_shared_za))
// CHECK-LABEL: @test_svst1_ver_vnum_za128(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[PG:%.*]])
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CHECK-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 3
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP2]]
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1q.vert(<vscale x 1 x i1> [[TMP0]], ptr [[TMP3]], i32 15, i32 [[SLICE_BASE:%.*]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z25test_svst1_ver_vnum_za128ju10__SVBool_tPn(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = tail call <vscale x 1 x i1> @llvm.aarch64.sve.convert.from.svbool.nxv1i1(<vscale x 16 x i1> [[PG:%.*]])
// CPP-CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CPP-CHECK-NEXT:    [[TMP2:%.*]] = mul i64 [[TMP1]], 3
// CPP-CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP2]]
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.st1q.vert(<vscale x 1 x i1> [[TMP0]], ptr [[TMP3]], i32 15, i32 [[SLICE_BASE:%.*]])
// CPP-CHECK-NEXT:    ret void
//
void test_svst1_ver_vnum_za128(uint32_t slice_base, svbool_t pg, __int128_t *base) {
  svst1_ver_vnum_za128(15, slice_base, 0, pg, base, 3);
}

//
//
__attribute__((arm_streaming_compatible, arm_shared_za))
// CHECK-LABEL: @test_svstr_vnum_za(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CHECK-NEXT:    [[TMP1:%.*]] = mul i64 [[TMP0]], 15
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP1]]
// CHECK-NEXT:    [[TMP3:%.*]] = add i32 [[SLICE_BASE:%.*]], 15
// CHECK-NEXT:    tail call void @llvm.aarch64.sme.str(i32 [[TMP3]], ptr [[TMP2]])
// CHECK-NEXT:    ret void
//
// CPP-CHECK-LABEL: @_Z18test_svstr_vnum_zajPh(
// CPP-CHECK-NEXT:  entry:
// CPP-CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.aarch64.sme.cntsb()
// CPP-CHECK-NEXT:    [[TMP1:%.*]] = mul i64 [[TMP0]], 15
// CPP-CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[BASE:%.*]], i64 [[TMP1]]
// CPP-CHECK-NEXT:    [[TMP3:%.*]] = add i32 [[SLICE_BASE:%.*]], 15
// CPP-CHECK-NEXT:    tail call void @llvm.aarch64.sme.str(i32 [[TMP3]], ptr [[TMP2]])
// CPP-CHECK-NEXT:    ret void
//
void test_svstr_vnum_za(uint32_t slice_base, uint8_t *base) {
  svstr_vnum_za(slice_base, 15, base);
}
