//===-- LinalgTransformEnums.td --------------------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef PYTHON_BINDINGS_LINALG_TRANSFORM_ENUMS
#define PYTHON_BINDINGS_LINALG_TRANSFORM_ENUMS

include "mlir/Dialect/Linalg/TransformOps/LinalgTransformEnums.td"

#endif // PYTHON_BINDINGS_LINALG_TRANSFORM_ENUMS
