; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -passes=infer-alignment -S < %s | FileCheck %s

@vector = external global <2 x i64>, align 16
@vector.arr = external global [13 x <2 x i64>], align 16

; ------------------------------------------------------------------------------
; 1d access
; ------------------------------------------------------------------------------

define void @load_vector(i32 %i) {
; CHECK-LABEL: define void @load_vector
; CHECK-SAME: (i32 [[I:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr <2 x i64>, ptr @vector, i32 [[I]]
; CHECK-NEXT:    [[LOAD:%.*]] = load <2 x i64>, ptr [[GEP]], align 16
; CHECK-NEXT:    ret void
;
  %gep = getelementptr <2 x i64>, ptr @vector, i32 %i
  %load = load <2 x i64>, ptr %gep, align 1
  ret void
}

define void @store_vector(i32 %i, <2 x i64> %y) {
; CHECK-LABEL: define void @store_vector
; CHECK-SAME: (i32 [[I:%.*]], <2 x i64> [[Y:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr <2 x i64>, ptr @vector, i32 [[I]]
; CHECK-NEXT:    store <2 x i64> [[Y]], ptr [[GEP]], align 16
; CHECK-NEXT:    ret void
;
  %gep = getelementptr <2 x i64>, ptr @vector, i32 %i
  store <2 x i64> %y, ptr %gep, align 1
  ret void
}

; ------------------------------------------------------------------------------
; 2d access
; ------------------------------------------------------------------------------

define void @load_vector_array(i32 %i, i32 %j) {
; CHECK-LABEL: define void @load_vector_array
; CHECK-SAME: (i32 [[I:%.*]], i32 [[J:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr [13 x <2 x i64>], ptr @vector.arr, i32 [[I]], i32 [[J]]
; CHECK-NEXT:    [[LOAD:%.*]] = load <2 x i64>, ptr [[GEP]], align 16
; CHECK-NEXT:    ret void
;
  %gep = getelementptr [13 x <2 x i64>], ptr @vector.arr, i32 %i, i32 %j
  %load = load <2 x i64>, ptr %gep, align 1
  ret void
}

define void @store_vector_array(i32 %i, i32 %j, <2 x i64> %y) {
; CHECK-LABEL: define void @store_vector_array
; CHECK-SAME: (i32 [[I:%.*]], i32 [[J:%.*]], <2 x i64> [[Y:%.*]]) {
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr [13 x <2 x i64>], ptr @vector.arr, i32 [[I]], i32 [[J]]
; CHECK-NEXT:    store <2 x i64> [[Y]], ptr [[GEP]], align 16
; CHECK-NEXT:    ret void
;
  %gep = getelementptr [13 x <2 x i64>], ptr @vector.arr, i32 %i, i32 %j
  store <2 x i64> %y, ptr %gep, align 1
  ret void
}
