; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt < %s -passes=infer-alignment -S | FileCheck %s

define i177 @ossfuzz_9880(i177 %X) {
; CHECK-LABEL: define i177 @ossfuzz_9880
; CHECK-SAME: (i177 [[X:%.*]]) {
; CHECK-NEXT:    [[A:%.*]] = alloca i177, align 8
; CHECK-NEXT:    [[L1:%.*]] = load i177, ptr [[A]], align 8
; CHECK-NEXT:    ret i177 [[L1]]
;
  %A = alloca i177
  %L1 = load i177, ptr %A
  ret i177 %L1
}
