; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt < %s -passes=no-op-function -S | FileCheck %s
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: nounwind uwtable
define i32 @foo1(ptr align 32 %a) #0 {
; CHECK-LABEL: define i32 @foo1
; CHECK-SAME: (ptr align 32 [[A:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[A]], align 4
; CHECK-NEXT:    ret i32 [[TMP0]]
;
entry:
  %0 = load i32, ptr %a, align 4
  ret i32 %0

}

define i32 @foo2(ptr align 32 %a) #0 {
; CHECK-LABEL: define i32 @foo2
; CHECK-SAME: (ptr align 32 [[A:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[V:%.*]] = call ptr @func1(ptr [[A]])
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[V]], align 4
; CHECK-NEXT:    ret i32 [[TMP0]]
;
entry:
  %v = call ptr @func1(ptr %a)
  %0 = load i32, ptr %v, align 4
  ret i32 %0

}

declare ptr @func1(ptr returned) nounwind

attributes #0 = { nounwind uwtable }
