// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 3
// RUN: %clang -O2 -fstrict-flex-arrays=3 -fsanitize=bounds -fsanitize=object-size -emit-llvm -S -o - %s | FileCheck %s

#define __counted_by(member)    __attribute__((__counted_by__(member)))

struct annotated {
  unsigned long flags;
  int count;
  int array[] __counted_by(count);
};

// CHECK-LABEL: define dso_local void @test1(
// CHECK-SAME: ptr noundef [[P:%.*]], i32 noundef [[INDEX:%.*]], i32 noundef [[VAL:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[COUNT:%.*]] = getelementptr inbounds [[STRUCT_ANNOTATED:%.*]], ptr [[P]], i64 0, i32 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COUNT]], align 8, !tbaa [[TBAA5:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = sext i32 [[INDEX]] to i64, !nosanitize !9
// CHECK-NEXT:    [[TMP2:%.*]] = zext i32 [[TMP0]] to i64, !nosanitize !9
// CHECK-NEXT:    [[TMP3:%.*]] = icmp ult i64 [[TMP1]], [[TMP2]], !nosanitize !9
// CHECK-NEXT:    br i1 [[TMP3]], label [[CONT7:%.*]], label [[HANDLER_OUT_OF_BOUNDS:%.*]], !prof [[PROF10:![0-9]+]], !nosanitize !9
// CHECK:       handler.out_of_bounds:
// CHECK-NEXT:    [[TMP4:%.*]] = zext i32 [[INDEX]] to i64, !nosanitize !9
// CHECK-NEXT:    tail call void @__ubsan_handle_out_of_bounds(ptr nonnull @[[GLOB2:[0-9]+]], i64 [[TMP4]]) #[[ATTR2:[0-9]+]], !nosanitize !9
// CHECK-NEXT:    br label [[CONT7]], !nosanitize !9
// CHECK:       cont7:
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [[STRUCT_ANNOTATED]], ptr [[P]], i64 0, i32 2, i64 [[TMP1]]
// CHECK-NEXT:    store i32 [[VAL]], ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA5]]
// CHECK-NEXT:    ret void
//
void test1(struct annotated *p, int index, int val) {
  p->array[index] = val;
}
